### ISSUE TITLE
Twitter returns different date formats

### ISSUE THREAD

**Issue by SpKiwi** [EvilAvenger/HashtagAggregator#11]
Twitter can return dates the following ways:
2017-04-09T12:40:57.9510494+00:00
2017-04-03T15:39:55.3418086

**Comment by EvilAvenger** [comment]
All dates for VK and Twitter are now in UTC.
e.g.
"postDate":"2017-04-11T19:40:01.8060191Z"
"postDate":"2017-04-11T19:34:34Z"
