### ISSUE TITLE
Add EF Core 2.0 update and change dbcontext creation to context pooling

### ISSUE THREAD

**Issue by EvilAvenger** [EvilAvenger/HashtagAggregator#20]
https://blogs.msdn.microsoft.com/dotnet/2017/05/12/announcing-ef-core-2-0-preview-1/

**Comment by EvilAvenger** [comment]
There are breaking changes in aspnet/Announcements##262

**Comment by EvilAvenger** [comment]
Added solution from IdentityServer/IdentityServer4#1055250

**Comment by springe2004** [comment]
i got,thanks!
